### ISSUE TITLE
UFDiine is causing my Wii U to hard reboot (with Tiramisu)

### ISSUE THREAD

**Issue by JoseHidalgo** [GaryOderNichts/UFDiine#1]
Hello, and thanks for this app of course :) 

In my case it doesn't work at all. I have opened a topic here : https://gbatemp.net/threads/ufdiine-is-bricking-my-console.608921/#post-9768886

I have a freshly Tiramisu-modded Wii U, with a USB hard drive. Everything works perfectly so far.

Unfortunately, launching UFDiine via the HBC instantly freezes the console. I mean, at the very moment I press the "Load" button, the whole thing freezes, and I have to hard reboot it via the console's on/off button. This can be reproduced 100% of the time.

Thanks in advance for your help !

**Comment by JoseHidalgo** [comment]
Like suggested in GBA forums, I was indeed using the Hombrew Launcher Channel, which doesn't work properly with Tiramisu.
Using the Mii Maker to launch UFDiine worked perfectly. :)

**Comment by danielhoherd** [comment]
I just ran into this issue. Thanks for leaving a comment with the fix @JoseHidalgo!
